Update README.rst
ESSS/cookiecutter-esss-pypackage pull request #3
Opened 2019-02-06 19:14 UTC by igorcandeia

2019-02-06 21:12 UTC, igortg commented on README.rst
> +Make sure to have an account on `PyPI`_
Again? You already warned about that in right above

2019-02-06 21:12 UTC, igortg commented on README.rst
>        1) travis encrypt --add deploy.password
Shouldn't the user install `travis` CLI first?

2019-02-06 21:12 UTC, igortg commented on README.rst
> +1. Log into your account at `ReadTheDocs`_ . If you don't have one, create one and log into it.
Leave just _Log in to your ReadTheDocs account_ on this line. The rest is pretty obvious

2019-02-07 10:58 UTC, nicoddemus requested changes
Overall good work!

2019-02-07 10:58 UTC, nicoddemus commented on README.rst
> +4.2 Activating Appveyor:
It is `AppVeyor` ;)

2019-02-07 10:58 UTC, nicoddemus commented on README.rst
> +.. code-block:: python
`.. code-block:: yaml`

2019-02-07 10:58 UTC, nicoddemus commented on README.rst
> +.. code-block:: python
`.. code-block:: yaml`

2019-02-07 10:58 UTC, nicoddemus commented on README.rst
> +
We should also mention that after the first release (made by pushing a tag), the project will appear on PyPI and the user should add more maintainers to it. 👍

2019-02-07 11:52 UTC, williamjamir approved these changes

2019-02-12 16:54 UTC, nicoddemus approved these changes

2019-02-13 12:25 UTC, merged